[package]
name = "onnxruntime-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ort = "1.13.3"
rand = "0.8.5"
tokenizers = "0.13.2"
