[package]
name = "onnxruntime-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
criterion = "0.4.0"
ndarray = "0.15.6"
ort = "1.13.3"
rand = "0.8.5"
tokenizers = "0.13.2"

[[bench]]
name = "bench_main"
harness = false
